### ISSUE TITLE
Ubuntu vagrant box support

### ISSUE THREAD

**Issue by kkohlbrenner** [geerlingguy/ansible-role-java#107]
Hi, as I understand this role will only work for boxes versioned previous to ubuntu1604, is that right? If so, are other similar boxes recommended?

**Comment by jserpapinto** [comment]
You can use it in any ubuntu, I believe. At least it works in `18.04`.

If you say that because of the `README` playbook examples section, what he means is that for ubuntu versions prior to `16.04`, you need to add the `apt_repository`.
