### ISSUE TITLE
Environment Variables

### ISSUE THREAD

**Issue by joao-fidalgo** [geerlingguy/ansible-role-java#17]
This playbook should add JAVA_HOME, JDK_HOME variables to environment and append JAVA_HOME to PATH.

Probably configurable thru variables.

**Comment by jermon** [comment]
I second this motion.

**Comment by fiunchinho** [comment]
👍

**Comment by geerlingguy** [comment]
I'd be willing to merge a PR that allows people to define global env vars in this way, especially if it can be done in a backwards-compatible way (and they aren't required). See my Solr role for some inspiration.

**Comment by geerlingguy** [comment]
I think I may at a minimum support the global setting of the JAVA_HOME var; it looks like I'll need it for some testing on certain platforms in Docker, e.g. https://travis-ci.org/geerlingguy/ansible-role-logstash/jobs/159052730

**Comment by geerlingguy** [comment]
I've added the ability to set JAVA_HOME—please let me know what you think!

**Comment by joao-fidalgo** [comment]
Will do.

**Comment by joao-fidalgo** [comment]
Thank you @geerlingguy. I'm sorry for the lack of feedback.

**Comment by jermon** [comment]
After just reading the code, I cant say that it solves the problem? 
I still need to know beforehand where where this role will install java and then figure out how to set this variable.  Maybe you could get this info from the package with something like dpkg -L

**Comment by Gaibhne** [comment]
Why is this marked as closed ? Jermon is right, this doesn't seem to be a very useful 'solution' at all :(
