### ISSUE TITLE
Intermittent failure on Google Compute instance

### ISSUE THREAD

**Issue by gregorskii** [geerlingguy/ansible-role-java#24]
Hi there,

I am seeing an intermittent issue on this role when installing on Debian Jessie 8 on a Google Compute instance. The error is:

```
googlecompute: failed: [default] (item=[u'openjdk-8-jdk']) => {"cache_update_time": 0, "cache_updated": false, "failed": true, "item": ["openjdk-8-jdk"], "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"     install 'openjdk-8-jdk'' failed: E: Failed to fetch http://httpredir.debian.org/debian/pool/main/p/pcsc-lite/libpcsclite1_1.8.13-1_amd64.deb  Error reading from server. Remote end closed connection [IP: 128.31.0.66 80]\n\nE: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?\n"
```

I am using `openjdk-8-jdk` but it fails intermittently using the default as well.

Do you have any ideas on how to fix this?

**Comment by timohund** [comment]
I had the same issue and could fix it by changing 

```
  apt: "name={{ item }} state=present"
```

to:

```
  apt: "name={{ item }} state=present update_cache=yes"
```

in tasks/setup-Debian.yml

@geerlingguy Do you think this should be change in the ansible-role or is something that uses the role responsible to do an apt-get update?

**Comment by timohund** [comment]
@geerlingguy @gregorskii i've created a PR if it makes sence for you, you can merge it :)

**Comment by geerlingguy** [comment]
@timohund - Thanks for the PR, but please see my note in the PR about the way I'd rather handle this—basically, in your playbook, if you're managing Debian/Ubuntu-flavored servers, manage the apt cache in `pre_tasks`:

```yaml
  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false
```

That's what I do in the test playbook for this role, and I'd rather not manage apt things that I don't need to directly in the role's tasks.
