### ISSUE TITLE
Error when specifying java_home with Ansible 2.2.1.0

### ISSUE THREAD

**Issue by MikeStankavich** [geerlingguy/ansible-role-java#32]
I'm bringing the discussion from pull request #27 over to an open issue so that we can track it against the upstream issue ansible/ansible#20392. 

In a nutshell, the error is this. If you set the java_home variable to anything other than empty string, you will get an error like the following with Ansible 2.2.1.0 and geerlingguy.java 1.7.2

`TASK [geerlingguy.java : Set JAVA_HOME if configured.] ************************* fatal: [default]: FAILED! => {"failed": true, "msg": "The conditional check 'java_home' failed. The error was: unexpected '/'\n line 1\n\nThe error appears to have been in '/vagrant/roles/geerlingguy.java/tasks/main.yml': line 33, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n# Environment setup.\n- name: Set JAVA_HOME if configured.\n ^ here\n"}`

You can work around this by changing https://github.com/geerlingguy/ansible-role-java/blob/master/tasks/main.yml#L38 to `when: java_home | default('') != ''` 

The workaround shouldn't have any side effects, so I can make a pull request if we want to just change that and not wait for the upstream fix.

**Comment by geerlingguy** [comment]
I'll give it a day or two, to see if there's any more 'official' upstream response (e.g. a hotfix release)—but barring that, I'd be willing to merge a PR that band-aids over the issue (for the sake of this issue queue!).

**Comment by MikeStankavich** [comment]
Agreed, looks like it's getting some attention upstream so let's wait for that to play out. Easy enough to implement the workaround locally in the short term.

**Comment by gmixa** [comment]
Hi, i dont set any value for the variable java_home and I get the similiar error on ubuntu xenial (desktop edition)

**Comment by geerlingguy** [comment]
@gmixa - Please use the workaround in the OP for now. I'm going to wait a little longer to see if a new Ansible release will fix this soon. (Otherwise stick to Ansible 2.2.0 for now—that's what I'm doing).

**Comment by MikeStankavich** [comment]
Hmm upstream closed the ticket stating that it's preferred to use `is defined`. I don't agree with that as `is defined` does not behave the same with empty strings. @geerlingguy do you think it's worth pursuing further upstream, or just change to a more explicit articulation of is defined and is not empty? 

FWIW I found that `var is defined and var != ''` also works, and while not quite as terse as `var | default('') != ''`, I think it reads easier and more clearly states the intent of the developer. 

I'm still happy to fire up a pull request if there's consensus that the more explicit syntax is the right direction to go.

**Comment by geerlingguy** [comment]
`var is defined and var != ''` works for me... I'm used to that pattern in PHP-land, and it makes enough sense to use it here.

**Comment by geerlingguy** [comment]
Fixed via @MikeStankavich's PR above.

**Comment by MikeStankavich** [comment]
Just a quick follow up, found a more concise syntax based on discussion in the upstream issue. Turns out that `var | default(false)` works the same as `var is defined and var != '`.  https://github.com/ansible/ansible/issues/20392#issuecomment-282305957

I doubt that it's worth running through another pull request just for that, but it's worth knowing for future reference.
