### ISSUE TITLE
fetching of openjdk-7-jdk failed on inital provisioning

### ISSUE THREAD

**Issue by robinlehrmann** [geerlingguy/ansible-role-java#36]
Hi,

I'm using your role with Debian jessie 8.7.

Currently I get a 404 http-response when ansible is try to install apt package.

I would suggest to add an update_cache: yes
Belongs to pull-request #37

**Comment by geerlingguy** [comment]
@robinlehrmann - Please see https://github.com/geerlingguy/ansible-role-java/pull/33 — basically we pulled that out of this role, and the intention is that you'd add the task on your playbook level itself (maybe in `pre_tasks`) instead.
