### ISSUE TITLE
Role breaks when skipping it

### ISSUE THREAD

**Issue by thokari** [geerlingguy/ansible-role-java#44]
I did this in my playbook:
```
- role: williamyeh.oracle-java
  java_version: 8
  java_subversion: 112
  java_set_javahome: true
  when: use_oracle_java
  tags: [ java ]

- role: geerlingguy.java
  when: not use_oracle_java
  tags: [ java ]
```

Result:
```
TASK [geerlingguy.java : Define java_packages.] ********************************
skipping: [qa-machine]

TASK [geerlingguy.java : Ensure Java is installed.] ****************************
fatal: [qa-machine]: FAILED! => {"failed": true, "msg": "'java_packages' is undefined"}
```

I guess the problem is that skipping the role leads to an error that crashes the role... :)

**Comment by geerlingguy** [comment]
Interesting; I skip it in my playbooks quite often without any issue... what version of Ansible are you running? I know there was a version that made things like this happen, but I haven't seen it in a while, on Ansible 2.2.1+

Also, for some scenarios, I have to add `static: no` to individual task include files so Ansible will evaluate them correctly.

**Comment by thokari** [comment]
Ok, thanks for responding, I will look into it again!
