### ISSUE TITLE
Role fails on Ubuntu

### ISSUE THREAD

**Issue by legovaer** [geerlingguy/ansible-role-java#5]
The role fails when using Vagrant's box hashicorp/precise64. 

TASK: [geerlingguy.java | Ensure Java is installed (Debian).] ***************** 
failed: [192.168.99.9] => (item=java-1.7.0-openjdk) => {"failed": true, "item": "java-1.7.0-openjdk"}
msg: No package matching 'java-1.7.0-openjdk' is available

**Comment by geerlingguy** [comment]
Can you try again, using the latest available version (`1.1.0`), which just got promoted to Galaxy?

It should pick the correct package for Debian now, which is `openjdk-7-jdk`.
