### ISSUE TITLE
Role causes [DEPRECATION WARNING] with ansible 2.4

### ISSUE THREAD

**Issue by jermon** [geerlingguy/ansible-role-java#55]
If you use this role with ansible 2.4 it will give you a warning

[DEPRECATION WARNING]: The use of 'include' for tasks has been deprecated. Use 
'import_tasks' for static inclusions or 'include_tasks' for dynamic inclusions.
 This feature will be removed in a future release. Deprecation warnings can be 
disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: include is kept for backwards compatibility but usage is
 discouraged. The module documentation details page may explain more about this
 rationale.. This feature will be removed in a future release. Deprecation 
warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: The use of 'static' has been deprecated. Use 
'import_tasks' for static inclusion, or 'include_tasks' for dynamic inclusion. 
This feature will be removed in a future release. Deprecation warnings can be 
disabled by setting deprecation_warnings=False in ansible.cfg.

It is my belief the the "includes" in tasks/main.yml should be replaced with 'include_tasks'.

**Comment by geerlingguy** [comment]
PR #56 is close, will merge once the review notes have been taken care of.
