### ISSUE TITLE
Ubuntu vs ubuntu

### ISSUE THREAD

**Issue by kallaics-liferay** [geerlingguy/ansible-role-java#62]
I am using this role under Ubuntu 16.04.
When my playbook is running using 2 times your playbook as dependency. The first run every time is successful (ansible_distribution = "**U**buntu"), but the second time (on different node, but with exactly same parameters) will be broken (ansible_distribution = "**u**buntu").  I don't find any reason how it's happen so I would like to suggest to fix the issue in the code. I will open PR soon, because the solution is very simple.

Possible solution: use "ansible_distribution| title" instead of "ansible_distribution" when Ubuntu is the host.

I will open PR with the solution..

**Comment by geerlingguy** [comment]
Weird; I wonder if that particular server is using a case sensitive filesystem, and that's the issue? It's really odd because this file include would be happening on your Ansible host running the playbook (unless maybe you're running the playbook local on that server?).
