### ISSUE TITLE
Is anyone adding support for Ubuntu 18.04?

### ISSUE THREAD

**Issue by mtbvang** [geerlingguy/ansible-role-java#69]
Is there a reason why this hasn't been done? I'll work on it now and PR.

**Comment by geerlingguy** [comment]
@mtbvang - This role has supported 18.04 for some time—see OS Platforms on Galaxy (https://galaxy.ansible.com/geerlingguy/java), and the most recent build success on 18.04 on Travis CI: https://travis-ci.org/geerlingguy/ansible-role-java/jobs/440394920
