### ISSUE TITLE
Time to start pushing Java 1.8?

### ISSUE THREAD

**Issue by bvansomeren** [geerlingguy/ansible-role-java#7]
Hi Jeff,

I'm opening this "issue" as a way to discuss this as it's not really an issue!

While OpenJDK 7 will continue to see updates from CentOS / Ubuntu, the Java world is moving on (slowly)
It's possible to use your role to install Java 8 (just specify the package); Maybe I can expand the documentation in your readme and provide an example?

Second, maybe at some point you might want to start defaulting to openjdk 8; What are your feelings on this subject?

I can create / test pull requests for both if you want.

**Comment by geerlingguy** [comment]
For now, you can specify the packages to be installed manually—https://github.com/geerlingguy/ansible-role-java/blob/master/defaults/main.yml#L4; of course, that presupposes the Java 8 packages are available in whatever repos your system is using.

I'd be happy to move to using Java 8 as the standard, but am mostly concerned with stability (more of a RHEL mindset), so I'd prefer to stick with system default packages (e.g. whatever packages come with the system), and allow users of the role to override by installing extra repos/PPAs and specifying `enablerepo` or `default_release` for this role to use them.

**Comment by bvansomeren** [comment]
Hi Jeff,

I totally understand; How about I start by forking and creating a pull request that includes some examples in the README.md of package names / combinations known to work with CentOS 6 and 7 for OpenJDK 1.8?

That way the default remains the same and we save whoever is using the role a few minutes. Win - Win right? :)

**Comment by geerlingguy** [comment]
Yep!

**Comment by bbaassssiiee** [comment]
If you are so concerned with stability and RHEL mindset, then why not support Oracle's JDK?
