### ISSUE TITLE
Deprecation Warning

### ISSUE THREAD

**Issue by budgester** [geerlingguy/ansible-role-java#85]
TASK [geerlingguy.java : Ensure Java is installed.] ****************************
       [DEPRECATION WARNING]: Invoking "apt" only once while using a loop via
       squash_actions is deprecated. Instead of using a loop to supply multiple items
       and specifying `name: "{{ item }}"`, please use `name: '{{ java_packages }}'`
       and remove the loop. This feature will be removed in version 2.11. Deprecation
       warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.

**Comment by geerlingguy** [comment]
This has been fixed for some time already; see:

- https://github.com/geerlingguy/ansible-role-java/blob/63debfb64de2e2de46ea2b9787de4b8146d0282e/tasks/setup-RedHat.yml#L4
- https://github.com/geerlingguy/ansible-role-java/blob/63debfb64de2e2de46ea2b9787de4b8146d0282e/tasks/setup-FreeBSD.yml#L4
- https://github.com/geerlingguy/ansible-role-java/blob/ee7c12b13aa594dc747892860e563f45794e94d0/tasks/setup-Debian.yml#L15

You may just need to update the role version in your requirements.yml file.
